
GET http://localhost:3000/user-api/users

###
POST http://127.0.0.1:3000/user-api/users
Content-Type: application/json

{
    "id":100,
    "name":"ravi",
    "age":25
}

###
PUT http://127.0.0.1:3000/user-api/users
Content-Type: application/json

{
    "id":10,
    "name":"swaragini",
    "age":20
}
###
GET http://localhost:3000/user-api/users/10

###
DELETE http://127.0.0.1:3000/user-api/users/10



###
GET http://localhost:3000/product-api/products

###
GET http://localhost:3000/product-api/products-id/11

###
GET http://localhost:3000/product-api/products-name/omen

###
POST http://localhost:3000/product-api/products
Content-Type: application/json


  {
    "productId": 11,
    "name": "laptop",
    "price": 210000,
    "brand": "hp-omen"
  }


###
PUT http://localhost:3000/product-api/products/11
Content-Type: application/json

{
    "productId":11,
    "name":"laptop",
    "price":215000,
    "brand":"hp-victus"
}

###

DELETE http://localhost:3000/product-api/products/11